server:
  port: 8011

spring:
  application:
    name: agile-form
#  main:
#    web-application-type: reactive
  threads:
    virtual:
      enabled: true

venti:
  jdbc:
    data-source:
#      url: jdbc:mysql://172.24.140.16:3306/agile_form
      url: jdbc:mysql://localhost:3306/guarantee
      user: zbz
      password: 123456